# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: rox87
      MONGO_INITDB_ROOT_PASSWORD: abc

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rox87
      ME_CONFIG_MONGODB_ADMINPASSWORD: abc
      ME_CONFIG_MONGODB_URL: mongodb://rox87:abc@mongo:27017/
      ME_CONFIG_BASICAUTH: false